spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/khmall_test?serverTimezone=Asia/Seoul
    username: ${DB_MYSQL_USER}
    password: ${DB_MYSQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
logging:
  level:
    root: info
    com.khmall: debug