name: Publish OpenAPI docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-dev"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build (skip tests)
        run: ./gradlew build -x test

      - name: Start app (doc profile, background)
        run: |
          nohup ./gradlew bootRun -Pargs=--spring.profiles.active=doc >/dev/null 2>&1 &
          for i in {1..40}; do
            if curl -fsS http://localhost:8080/v3/api-docs >/dev/null; then
              echo "OpenAPI endpoint is up"
              break
            fi
            echo "Waiting for app... ($i)"
            sleep 2
          done

      - name: Export OpenAPI JSON
        run: |
          mkdir -p build/docs
          curl -fsS http://localhost:8080/v3/api-docs > build/docs/openapi.json
          test -s build/docs/openapi.json

      - name: Create static Swagger UI
        run: |
          mkdir -p build/docs
          cat > build/docs/index.html <<'HTML'
          <!doctype html><html><head>
            <meta charset="utf-8"/>
            <title>API Docs</title>
            <meta name="viewport" content="width=device-width,initial-scale=1"/>
            <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist/swagger-ui.css"/>
          </head><body>
            <div id="swagger-ui"></div>
            <script src="https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js"></script>
            <script>
              window.onload = () => {
                window.ui = SwaggerUIBundle({
                  url: 'openapi.json',
                  dom_id: '#swagger-ui'
                });
              };
            </script>
          </body></html>
          HTML

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
